version: '3.8'
services:
   client:
      build:
         context: ./frontend
         dockerfile: Dockerfile
      tty: true
      ports:
         - "5049:5049"
      volumes:
         - ./frontend:/app
         - /app/node_modules
      networks:
         - backend   
   api:
      build: 
         context: ./backend
         dockerfile: Dockerfile
      command: python app.py
      #flask --app app.py --debug run
      #command: gunicorn --bind 0.0.0.0:5050 app:app
      ports:
         - "5050:5050"
      networks:
         - frontend
         - backend

networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge