version: '3.8'
services:
   client:
      build:
         context: ./frontend
         dockerfile: Dockerfile
      tty: true
      ipc: host
      ports:
         - "5049:5049"
         - 3000:3000
      volumes:
         - ./frontend:/app
         - /app/node_modules
      networks:
         - backend   
   api:
      build: 
         context: ./backend
         dockerfile: Dockerfile
      command: python app.py
      ports:
         - 5050:5050
         - 5000:5000
      networks:
         - frontend
         - backend
      volumes:
         - ./backend:/app

networks:
   frontend:
      driver: bridge
   backend:
      driver: bridge