version: "3.8"
services:
  mistral-serve:
    ipc: host
    ports:
      - 5555:5555
    build:
      context: .
      dockerfile: Dockerfile
    image: "alv/mistral-serve:debug"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    tty: true 
    volumes:
      - /home/dsc-admin/Documents/mis-thon/mistral_ft:/exp